/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ], // ← comma was missing here
  theme: {
    extend: {
      colors: {
        background: "#f7f9fb",
        "tertiary-fixed": "#d5e3fd",
        "primary-container": "#131b2e",
        "tertiary-container": "#0d1c2f",
        "primary-fixed": "#dae2fd",
        primary: "#000000",
        "outline-variant": "#c6c6cd",
        "on-primary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#565e74",
        "primary-fixed-dim": "#bec6e0",
        "on-error-container": "#93000a",
        "secondary-container": "#fed65b",
        "on-tertiary-container": "#76859b",
        outline: "#76777d",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed": "#241a00",
        "on-secondary-fixed-variant": "#574500",
        "on-primary-fixed": "#131b2e",
        surface: "#f7f9fb",
        "on-surface-variant": "#45464d",
        tertiary: "#000000",
        "on-tertiary-fixed-variant": "#3a485c",
        "error-container": "#ffdad6",
        "inverse-primary": "#bec6e0",
        "on-secondary-container": "#745c00",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#e9c349",
        "on-primary-container": "#7c839b",
        error: "#ba1a1a",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#0d1c2f",
        "surface-container-low": "#f2f4f6",
        "on-surface": "#191c1e",
        "secondary-fixed": "#ffe088",
        secondary: "#735c00",
        "on-background": "#191c1e",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "inverse-surface": "#2d3133",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#b9c7e0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "section-gap-lg": "80px",
        "section-gap-sm": "40px",
        base: "8px",
        gutter: "24px",
        "container-max": "1280px",
        "touch-target": "44px",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "admin-data": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "admin-data": ["13px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};